services:
  mysql:
    restart: always
    image: mysql:8.0.37
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Shanghai
    volumes:
      - ./data/etc/my.cnf:/etc/my.cnf
      - ./data/var/lib/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1s
      timeout: 3s
      retries: 10
